<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cloud.codestore</groupId>
        <artifactId>desktop-app</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>bundle</artifactId>
    <packaging>pom</packaging>

    <properties>
        <spring.profile>default</spring.profile>
        <target.platform/>
        <create.runtime.script/>
        <create.package.script/>
        <start.scripts/>
        <inno.setup.path/>
        <inno.setup.skip>true</inno.setup.skip>
    </properties>

    <dependencies>
        <!-- Required to enforce build order -->
        <dependency>
            <groupId>cloud.codestore</groupId>
            <artifactId>client-application</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>cloud.codestore</groupId>
            <artifactId>application</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <spring.profile>dev</spring.profile>
            </properties>
        </profile>

        <profile>
            <id>windows</id>
            <properties>
                <target.platform>windows</target.platform>
                <start.scripts>*.cmd</start.scripts>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <id>create Windows installer</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <skip>${inno.setup.skip}</skip>
                                    <executable>${inno.setup.path}/ISCC.exe</executable>
                                    <arguments>
                                        <argument>
                                            ${project.basedir}/platform/windows/windows-bundle-config.iss
                                        </argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>skip-windows-installer-creation</id>
            <activation>
                <property>
                    <name>inno.setup.path</name>
                </property>
            </activation>
            <properties>
                <inno.setup.skip>false</inno.setup.skip>
            </properties>
        </profile>
        <profile>
            <id>source-platform-windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <create.runtime.script>createRuntime.cmd</create.runtime.script>
                <create.package.script>createPackage.cmd</create.package.script>
            </properties>
        </profile>

        <profile>
            <id>linux</id>
            <properties>
                <target.platform>linux</target.platform>
                <start.scripts>*.sh</start.scripts>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.0.0</version>
                        <executions>
                            <execution>
                                <id>create snap package</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <workingDirectory>${project.basedir}</workingDirectory>
                                    <executable>
                                        ${project.basedir}/platform/${target.platform}/${create.package.script}
                                    </executable>
                                    <arguments>
                                        <argument>${project.version}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>source-platform-linux</id>
            <activation>
                <os>
                    <name>Linux</name>
                </os>
            </activation>
            <properties>
                <create.runtime.script>createRuntime.sh</create.runtime.script>
                <create.package.script>createPackage.sh</create.package.script>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <!-- Copy core and client binaries -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>copy core binaries</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/application/core</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.parent.basedir}/core/application/target/bin</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy client binaries</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/application/client</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.parent.basedir}/client/client-application/target/bin</directory>
                                    <excludes>
                                        <exclude>javafx-*.jar</exclude>
                                    </excludes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy start scripts</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/application</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/profile/${spring.profile}</directory>
                                    <includes>
                                        <include>${start.scripts}</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>create java runtime</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <executable>
                                ${project.basedir}/platform/${target.platform}/${create.runtime.script}
                            </executable>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>